<?php
namespace martdb;

/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

class MartdbRequest
{
    static public $isValidate = false;

    static public $_TSPEC = array(
        1 => array(
            'var' => 'id',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        2 => array(
            'var' => 'sender',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        3 => array(
            'var' => 'time',
            'isRequired' => false,
            'type' => TType::I64,
        ),
        4 => array(
            'var' => 'tag',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        5 => array(
            'var' => 'method',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
        6 => array(
            'var' => 'params',
            'isRequired' => false,
            'type' => TType::STRING,
        ),
    );

    /**
     * @var string
     */
    public $id = null;
    /**
     * @var string
     */
    public $sender = null;
    /**
     * @var int
     */
    public $time = null;
    /**
     * @var string
     */
    public $tag = null;
    /**
     * @var string
     */
    public $method = null;
    /**
     * @var string
     */
    public $params = null;

    public function __construct($vals = null)
    {
        if (is_array($vals)) {
            if (isset($vals['id'])) {
                $this->id = $vals['id'];
            }
            if (isset($vals['sender'])) {
                $this->sender = $vals['sender'];
            }
            if (isset($vals['time'])) {
                $this->time = $vals['time'];
            }
            if (isset($vals['tag'])) {
                $this->tag = $vals['tag'];
            }
            if (isset($vals['method'])) {
                $this->method = $vals['method'];
            }
            if (isset($vals['params'])) {
                $this->params = $vals['params'];
            }
        }
    }

    public function getName()
    {
        return 'MartdbRequest';
    }


    public function read($input)
    {
        $xfer = 0;
        $fname = null;
        $ftype = 0;
        $fid = 0;
        $xfer += $input->readStructBegin($fname);
        while (true) {
            $xfer += $input->readFieldBegin($fname, $ftype, $fid);
            if ($ftype == TType::STOP) {
                break;
            }
            switch ($fid) {
                case 1:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->id);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 2:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->sender);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 3:
                    if ($ftype == TType::I64) {
                        $xfer += $input->readI64($this->time);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 4:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->tag);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 5:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->method);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                case 6:
                    if ($ftype == TType::STRING) {
                        $xfer += $input->readString($this->params);
                    } else {
                        $xfer += $input->skip($ftype);
                    }
                    break;
                default:
                    $xfer += $input->skip($ftype);
                    break;
            }
            $xfer += $input->readFieldEnd();
        }
        $xfer += $input->readStructEnd();
        return $xfer;
    }

    public function write($output)
    {
        $xfer = 0;
        $xfer += $output->writeStructBegin('MartdbRequest');
        if ($this->id !== null) {
            $xfer += $output->writeFieldBegin('id', TType::STRING, 1);
            $xfer += $output->writeString($this->id);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->sender !== null) {
            $xfer += $output->writeFieldBegin('sender', TType::STRING, 2);
            $xfer += $output->writeString($this->sender);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->time !== null) {
            $xfer += $output->writeFieldBegin('time', TType::I64, 3);
            $xfer += $output->writeI64($this->time);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->tag !== null) {
            $xfer += $output->writeFieldBegin('tag', TType::STRING, 4);
            $xfer += $output->writeString($this->tag);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->method !== null) {
            $xfer += $output->writeFieldBegin('method', TType::STRING, 5);
            $xfer += $output->writeString($this->method);
            $xfer += $output->writeFieldEnd();
        }
        if ($this->params !== null) {
            $xfer += $output->writeFieldBegin('params', TType::STRING, 6);
            $xfer += $output->writeString($this->params);
            $xfer += $output->writeFieldEnd();
        }
        $xfer += $output->writeFieldStop();
        $xfer += $output->writeStructEnd();
        return $xfer;
    }
}
